# SEO settings
title: "Morysky's blog"
title2: "" # default: ""
description: "Morysky's blog"
keywords: ""
url: blog.morysky.win # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

repo: http://github.com/morysky
disqus_shortname: "syaokun219"
idcomments_acct: "fe038a09c4e22c1f95fc4bbf374b8e73"
twitter_username: "syaokun219"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Morysky"
  job      : "PHP R&D Software Engineer @Baidu"
  bio      : ""
  thumb    : /assets/image/avatar1_meitu_small.jpg
  email    : 627571@qq.com
  url      : http://morysky.github.io
  github   : http://github.com/morysky
  twitter  : http://twitter.com/syaokun219
  facebook : https://www.facebook.com/syaokun219?ref=bookmarks
  linkedin : http://linkedin.com/in/syaokun219

# social settings
og_locale: "Beijing"
twitter_card: "summary_large_image"
twitter_site: "@syaokun219"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
